name: flutter_gyw
version: 1.1.2

publish_to: none

homepage: https://www.getyourway.be

description: A package to manage connections with aRdent smart glasses.

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: '>=1.17.0'

dependencies:
  flutter_blue_plus: ^1.5.2
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.1
  dartdoc: ^6.2.2
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/icons/
