name: flutter_gyw
description: A package to manage connections with GYW devices.
version: 0.1.0
homepage:

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_blue_plus: ^1.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  dart_code_metrics: ^4.19.1
  dartdoc: ^6.1.1

flutter:
  assets:
    - assets/icons/
