name: flutter_gyw
version: 1.2.1
description: A package to manage interactions with aRdent smart glasses.
repository: https://github.com/getyourway/flutter_gyw/

publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_blue_plus: ^1.31.4
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0

dev_dependencies:
  analyzer: ^6.4.1
  build_runner: ^2.4.9
  dartdoc: ^8.0.8
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  json_serializable: ^6.8.0

flutter:
  assets:
    - assets/icons/
