name: flutter_gyw
version: 1.2.0
description: A package to manage interactions with aRdent smart glasses.
repository: https://github.com/getyourway/flutter_gyw/

publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_blue_plus: ^1.31.4

dev_dependencies:
  dartdoc: ^6.3.0
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/icons/
