name: flutter_gyw
version: 0.2.3
publish_to: https://onepub.dev/api/xvppsdavuh
homepage: https://www.getyourway.be

description: A package to manage connections with GYW devices.

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: '>=1.17.0'

dependencies:
  flutter_blue_plus: ^1.3.1
  flutter:
    sdk: flutter
  bluetooth_state: ^0.0.1

dev_dependencies:
  flutter_lints: ^2.0.0
  dart_code_metrics: ^4.19.1
  dartdoc: ^6.1.1
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/icons/
