name: flutter_gyw
version: 1.1.3

publish_to: none

homepage: https://www.getyourway.be

description: A package to manage interactions with aRdent smart glasses.

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: '>=1.17.0'

dependencies:
  flutter_blue_plus: ^1.15.5
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.3
  dartdoc: ^6.3.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/icons/
